import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import pg from "pg";

const { Pool } = pg;
const migrationUrl = new URL("../docs/sql/014_chargebee_subscription_payment_allocation.sql", import.meta.url);
const connectionString = process.env.PTB_CHARGEBEE_POSTGRES_INTEGRATION_URL;

function validatedLocalTestUrl(value) {
  if (!value) return null;
  const url = new URL(value);
  const localHosts = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);
  const database = decodeURIComponent(url.pathname.replace(/^\//, ""));
  if (!localHosts.has(url.hostname)) {
    throw new Error("PTB_CHARGEBEE_POSTGRES_INTEGRATION_URL must use a loopback host");
  }
  if (!/^ptb_chargebee_subscription_test(?:_[a-z0-9_]+)?$/i.test(database)) {
    throw new Error("PTB_CHARGEBEE_POSTGRES_INTEGRATION_URL must target a dedicated ptb_chargebee_subscription_test database");
  }
  if (decodeURIComponent(url.username) !== "ptb_chargebee_test") {
    throw new Error("PTB_CHARGEBEE_POSTGRES_INTEGRATION_URL must use ptb_chargebee_test");
  }
  return url.toString();
}

const localUrl = validatedLocalTestUrl(connectionString);

test("Chargebee subscription allocation on isolated PostgreSQL", {
  skip: !localUrl && "local isolated PostgreSQL prerequisite unavailable"
}, async t => {
  const pool = new Pool({ connectionString: localUrl, max: 12, ssl: false });
  const migration = await readFile(migrationUrl, "utf8");

  const reset = async () => {
    await pool.query(`TRUNCATE TABLE
      public.chargebee_subscription_payment_trees,
      public.chargebee_subscription_payments,
      public.chargebee_subscription_billing_periods,
      public.chargebee_tree_subscriptions,
      public.trees1,
      public.users1 RESTART IDENTITY CASCADE`);
  };

  const seedTrees = async count => {
    await pool.query(`INSERT INTO public.trees1
      (tree_code, tree_type, lat, "long", planted_date, is_claimed)
      SELECT 'CB-TEST-' || lpad(value::text, 5, '0'), 'Cashew',
             8.96356199, -12.52373404, DATE '2025-01-02', false
      FROM generate_series(1, $1::integer) AS value`, [count]);
  };

  const payment = async (queryable, {
    transaction, subscription, plan = "1-boom-per-maand-EUR-Monthly",
    email = "chargebee@example.test", paidAt = "2026-01-02T10:00:00Z",
    periodStart = "2026-01-01T00:00:00Z", periodEnd = "2026-02-01T00:00:00Z",
    startedAt = "2026-01-01T00:00:00Z", invoice = "invoice-test",
    lineItem = "line-test", customer = "customer-test", amountMinor = 1000,
    createdAt = "2026-01-01T00:00:00Z"
  }) => (await queryable.query(`SELECT *
    FROM public.process_chargebee_subscription_payment(
      $1, $2, $3, $4, $5::timestamptz, $6::timestamptz,
      $7::timestamptz, $8, $9, $10, 'Test', 'Customer', 'active',
      $11::timestamptz, $12::bigint, 'EUR', $13::timestamptz
    )`, [
      transaction, subscription, plan, email, paidAt, periodStart,
      periodEnd, invoice, lineItem, customer, startedAt, amountMinor, createdAt
    ])).rows[0];

  try {
    await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public");
    await pool.query(`CREATE TABLE public.users1 (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email varchar NOT NULL,
      first_name varchar,
      last_name varchar,
      chargebee_id varchar,
      subscription_type varchar,
      subscription_info jsonb,
      created_at timestamp without time zone NOT NULL DEFAULT now(),
      updated_at timestamp without time zone NOT NULL DEFAULT now()
    )`);
    await pool.query("CREATE UNIQUE INDEX users1_normalized_email_unique_idx ON public.users1 (lower(trim(email)))");
    await pool.query(`CREATE TABLE public.trees1 (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id integer REFERENCES public.users1(id),
      lat numeric,
      "long" numeric,
      planted_date date,
      purchase_date timestamp without time zone,
      tree_code varchar,
      tree_type varchar,
      order_id varchar(50),
      reserved_token text,
      claimed_at timestamptz,
      claim_email_sent_at timestamptz,
      unclaimed_user_id integer,
      is_claimed boolean DEFAULT false,
      created_at timestamp without time zone NOT NULL DEFAULT now(),
      updated_at timestamp without time zone NOT NULL DEFAULT now()
    )`);
    await pool.query(migration);
    await pool.query(`INSERT INTO public.chargebee_subscription_cutover_policy
      (singleton, cutover_at) VALUES (true, '2026-01-01T00:00:00Z')`);

    await t.test("migration exposes the five operational tables, cutover policy and both public functions", async () => {
      const result = await pool.query(`SELECT
        to_regclass('public.chargebee_subscription_plans') IS NOT NULL AS plans,
        to_regclass('public.chargebee_tree_subscriptions') IS NOT NULL AS subscriptions,
        to_regclass('public.chargebee_subscription_billing_periods') IS NOT NULL AS periods,
        to_regclass('public.chargebee_subscription_payments') IS NOT NULL AS payments,
        to_regclass('public.chargebee_subscription_payment_trees') IS NOT NULL AS payment_trees,
        to_regclass('public.chargebee_subscription_cutover_policy') IS NOT NULL AS cutover_policy,
        to_regprocedure('public.mark_chargebee_subscription_payment_side_effect(text,text,text,text,text,text)') IS NOT NULL AS marker`);
      assert.deepEqual(result.rows[0], {
        plans: true, subscriptions: true, periods: true,
        payments: true, payment_trees: true, cutover_policy: true, marker: true
      });
    });

    await t.test("identical transaction replay returns the original tree", async () => {
      await reset(); await seedTrees(3);
      const input = { transaction: "txn-replay", subscription: "sub-replay" };
      const first = await payment(pool, input);
      const retry = await payment(pool, input);
      assert.equal(retry.duplicate, true);
      assert.deepEqual(retry.assigned_trees, first.assigned_trees);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM chargebee_subscription_payments")).rows[0].count, 1);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM chargebee_subscription_payment_trees")).rows[0].count, 1);
    });

    await t.test("concurrent transactions in one billing period make two events and one allocation", async () => {
      await reset(); await seedTrees(4);
      const base = { subscription: "sub-same-period", invoice: "inv-same-period" };
      const [a, b] = await Promise.all([
        payment(pool, { ...base, transaction: "txn-same-a", lineItem: "line-a" }),
        payment(pool, { ...base, transaction: "txn-same-b", lineItem: "line-b" })
      ]);
      assert.deepEqual([a.payment_event_number, b.payment_event_number].sort(), [1, 2]);
      assert.deepEqual([a.billing_period_number, b.billing_period_number], [1, 1]);
      assert.equal([a, b].filter(row => row.allocation_period_reused).length, 1);
      assert.equal([a, b].filter(row => row.welcome_required).length, 1);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM chargebee_subscription_billing_periods")).rows[0].count, 1);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM chargebee_subscription_payment_trees")).rows[0].count, 1);
    });

    await t.test("concurrent subscriptions competing for trees receive distinct rows", async () => {
      await reset(); await seedTrees(2);
      const [a, b] = await Promise.all([
        payment(pool, { transaction: "txn-concurrent-a", subscription: "sub-concurrent-a", email: "a@example.test" }),
        payment(pool, { transaction: "txn-concurrent-b", subscription: "sub-concurrent-b", email: "b@example.test" })
      ]);
      assert.notEqual(a.assigned_trees[0].tree_id, b.assigned_trees[0].tree_id);
      assert.equal((await pool.query("SELECT count(DISTINCT tree_id)::int AS count FROM chargebee_subscription_payment_trees")).rows[0].count, 2);
    });

    await t.test("unknown plan and insufficient inventory leave no operational rows", async () => {
      await reset(); await seedTrees(1);
      await assert.rejects(payment(pool, {
        transaction: "txn-unknown", subscription: "sub-unknown", plan: "unknown-plan"
      }), /Unknown or inactive Chargebee plan/);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM chargebee_tree_subscriptions")).rows[0].count, 0);
      await assert.rejects(payment(pool, {
        transaction: "txn-short", subscription: "sub-short",
        plan: "20-euro-24-bomen-abonnement-EUR-Monthly"
      }), /Insufficient free trees/);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM chargebee_subscription_payments")).rows[0].count, 0);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM trees1 WHERE user_id IS NOT NULL")).rows[0].count, 0);
    });

    await t.test("all calendar patterns use billing month offset instead of event sequence", async () => {
      const cases = [
        ["5-euro-6-bomen-abonnement-EUR-Monthly", [1,0,1,0,1,0,1,0,1,0,1,0]],
        ["750-9-bomen-abonnement-EUR-Monthly", [1,1,0,1,1,1,0,1,1,1,0,1]],
        ["1-boom-per-maand-EUR-Monthly", Array(12).fill(1)],
        ["12-5-euro-15-bomen-abonnement-EUR-Monthly", [2,1,1,1,2,1,1,1,2,1,1,1]],
        ["15-boom-per-maand-EUR-Monthly", [2,1,2,1,2,1,2,1,2,1,2,1]],
        ["17-5-euro-21-bomen-abonnement-EUR-Monthly", [2,2,1,2,2,2,1,2,2,2,1,2]],
        ["20-euro-24-bomen-abonnement-EUR-Monthly", Array(12).fill(2)]
      ];
      for (const [caseIndex, [plan, expected]] of cases.entries()) {
        await reset(); await seedTrees(30);
        const actual = [];
        for (let month = 0; month < 12; month += 1) {
          const start = new Date(Date.UTC(2026, month, 1));
          const end = new Date(Date.UTC(2026, month + 1, 1));
          const result = await payment(pool, {
            transaction: `txn-pattern-${caseIndex}-${month}`,
            subscription: `sub-pattern-${caseIndex}`,
            plan,
            periodStart: start.toISOString(), periodEnd: end.toISOString(),
            paidAt: new Date(start.getTime() + 86400000).toISOString()
          });
          actual.push(result.trees_due);
        }
        assert.deepEqual(actual, expected, plan);
      }
    });

    await t.test("plan change starts only on the new billing period", async () => {
      await reset(); await seedTrees(5);
      await payment(pool, { transaction: "txn-plan-1", subscription: "sub-plan" });
      const changed = await payment(pool, {
        transaction: "txn-plan-2", subscription: "sub-plan",
        plan: "20-euro-24-bomen-abonnement-EUR-Monthly",
        periodStart: "2026-02-01T00:00:00Z", periodEnd: "2026-03-01T00:00:00Z",
        paidAt: "2026-02-02T00:00:00Z", invoice: "invoice-plan-2"
      });
      assert.equal(changed.billing_period_number, 2);
      assert.equal(changed.trees_due, 2);
      assert.equal((await pool.query("SELECT plan_changed FROM chargebee_subscription_billing_periods WHERE billing_period_number=2")).rows[0].plan_changed, true);
      await assert.rejects(payment(pool, {
        transaction: "txn-plan-conflict", subscription: "sub-plan",
        plan: "20-euro-24-bomen-abonnement-EUR-Monthly"
      }), /already registered with plan/);
    });

    await t.test("cutover seed suppresses initial effects without invented history", async () => {
      await reset(); await seedTrees(3);
      const user = (await pool.query("INSERT INTO users1(email) VALUES ('seeded@example.test') RETURNING id")).rows[0];
      await pool.query(`INSERT INTO chargebee_tree_subscriptions(
        chargebee_subscription_id,user_id,customer_email,current_plan_id,
        current_trees_per_year,current_allocation_pattern,
        initial_side_effects_suppressed,welcome_status,status,started_at
      ) VALUES (
        'sub-seeded',$1,'seeded@example.test','12-5-euro-15-bomen-abonnement-EUR-Monthly',
        15,ARRAY[2,1,1,1,2,1,1,1,2,1,1,1]::smallint[],true,'not_required','active','2025-01-01'
      )`, [user.id]);
      const result = await payment(pool, {
        transaction: "txn-seeded-first-local", subscription: "sub-seeded",
        plan: "12-5-euro-15-bomen-abonnement-EUR-Monthly",
        email: "seeded@example.test", startedAt: "2025-01-01T00:00:00Z",
        periodStart: "2026-02-01T00:00:00Z", periodEnd: "2026-03-01T00:00:00Z",
        paidAt: "2026-02-02T00:00:00Z", createdAt: null
      });
      assert.equal(result.billing_period_number, 1);
      assert.equal(result.payment_event_number, 1);
      assert.equal(result.trees_allocated, 1);
      assert.equal(result.is_first_payment, false);
      assert.equal(result.welcome_required, false);
      assert.equal(result.certificate_required, false);
      const replay = await payment(pool, {
        transaction: "txn-seeded-first-local", subscription: "sub-seeded",
        plan: "12-5-euro-15-bomen-abonnement-EUR-Monthly",
        email: "seeded@example.test", startedAt: "2025-01-01T00:00:00Z",
        periodStart: "2026-02-01T00:00:00Z", periodEnd: "2026-03-01T00:00:00Z",
        paidAt: "2026-02-02T00:00:00Z", createdAt: null
      });
      assert.equal(replay.duplicate, true);
      const secondEvent = await payment(pool, {
        transaction: "txn-seeded-second-event", subscription: "sub-seeded",
        plan: "12-5-euro-15-bomen-abonnement-EUR-Monthly",
        email: "seeded@example.test", startedAt: "2025-01-01T00:00:00Z",
        periodStart: "2026-02-01T00:00:00Z", periodEnd: "2026-03-01T00:00:00Z",
        paidAt: "2026-02-03T00:00:00Z", invoice: "invoice-seeded-second",
        createdAt: null
      });
      assert.equal(secondEvent.payment_event_number, 2);
      assert.equal(secondEvent.trees_allocated, 0);
      const changed = await payment(pool, {
        transaction: "txn-seeded-plan-change", subscription: "sub-seeded",
        plan: "20-euro-24-bomen-abonnement-EUR-Monthly",
        email: "seeded@example.test", startedAt: "2025-01-01T00:00:00Z",
        periodStart: "2026-03-01T00:00:00Z", periodEnd: "2026-04-01T00:00:00Z",
        paidAt: "2026-03-02T00:00:00Z", invoice: "invoice-seeded-plan-change",
        createdAt: null
      });
      assert.equal(changed.billing_period_number, 2);
      assert.equal(changed.payment_event_number, 3);
      assert.equal(changed.welcome_required, false);
      assert.equal(changed.certificate_required, false);
      assert.equal((await pool.query("SELECT initial_side_effects_suppressed FROM chargebee_tree_subscriptions WHERE chargebee_subscription_id='sub-seeded'")).rows[0].initial_side_effects_suppressed, true);
    });

    await t.test("cutover classification fails closed and boundary timestamps are new", async () => {
      await reset(); await seedTrees(4);
      const before = async () => (await pool.query(`SELECT
        (SELECT count(*)::int FROM chargebee_tree_subscriptions) AS subscriptions,
        (SELECT count(*)::int FROM chargebee_subscription_payments) AS payments`)).rows[0];
      assert.deepEqual(await before(), { subscriptions: 0, payments: 0 });
      await assert.rejects(payment(pool, {
        transaction: "txn-missed", subscription: "sub-missed",
        createdAt: "2025-12-31T23:59:59Z"
      }), /manual review/);
      assert.deepEqual(await before(), { subscriptions: 0, payments: 0 });
      await assert.rejects(payment(pool, {
        transaction: "txn-no-created", subscription: "sub-no-created", createdAt: null
      }), /created_at is required/);
      assert.deepEqual(await before(), { subscriptions: 0, payments: 0 });
      await pool.query("DELETE FROM chargebee_subscription_cutover_policy");
      await assert.rejects(payment(pool, {
        transaction: "txn-no-policy", subscription: "sub-no-policy"
      }), /cutover policy is not configured/);
      assert.deepEqual(await before(), { subscriptions: 0, payments: 0 });
      await pool.query(`INSERT INTO chargebee_subscription_cutover_policy(singleton, cutover_at)
        VALUES (true, '2026-01-01T00:00:00Z')`);
      const boundary = await payment(pool, {
        transaction: "txn-boundary", subscription: "sub-boundary",
        createdAt: "2026-01-01T00:00:00Z"
      });
      assert.equal(boundary.welcome_required, true);
      assert.equal(boundary.certificate_required, true);
    });

    await t.test("completed side effects are terminal and matching callbacks are idempotent", async () => {
      await reset(); await seedTrees(2);
      await payment(pool, { transaction: "txn-side-effect", subscription: "sub-side-effect" });
      const args = ["txn-side-effect", "welcome_email", "completed", "mail-1", null, null];
      await pool.query("SELECT mark_chargebee_subscription_payment_side_effect($1,$2,$3,$4,$5,$6)", args);
      await pool.query("SELECT mark_chargebee_subscription_payment_side_effect($1,$2,$3,$4,$5,$6)", args);
      await assert.rejects(pool.query(
        "SELECT mark_chargebee_subscription_payment_side_effect($1,'welcome_email','failed',NULL,NULL,'late')",
        ["txn-side-effect"]
      ), /terminal/);
      await pool.query("SELECT mark_chargebee_subscription_payment_side_effect($1,'certificate','completed',$2,$3,NULL)", [
        "txn-side-effect", "certificate-mail-1", "https://example.invalid/certificate.pdf"
      ]);
      const state = (await pool.query("SELECT welcome_status FROM chargebee_tree_subscriptions")).rows[0];
      assert.equal(state.welcome_status, "completed");
    });
  } finally {
    await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public").catch(() => {});
    await pool.end();
  }
});

export { validatedLocalTestUrl };
