import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import pg from "pg";

const { Pool } = pg;
const migrationUrl = new URL("../docs/sql/011_shopify_subscription_tree_allocation.sql", import.meta.url);
const connectionString = process.env.PTB_POSTGRES_INTEGRATION_URL;

function validatedLocalTestUrl(value) {
  if (!value) return null;
  const url = new URL(value);
  const localHosts = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);
  const database = decodeURIComponent(url.pathname.replace(/^\//, ""));
  if (!localHosts.has(url.hostname)) throw new Error("PTB_POSTGRES_INTEGRATION_URL must use localhost, 127.0.0.1 or ::1");
  if (!/^ptb_shopify_subscription_test(?:_[a-z0-9_]+)?$/i.test(database)) {
    throw new Error("PTB_POSTGRES_INTEGRATION_URL must target a dedicated ptb_shopify_subscription_test database");
  }
  return url.toString();
}

const localUrl = validatedLocalTestUrl(connectionString);

test("Shopify subscription allocation on isolated PostgreSQL", { skip: !localUrl && "local isolated PostgreSQL prerequisite unavailable" }, async t => {
  const pool = new Pool({ connectionString: localUrl, max: 8, ssl: false });
  const migration = await readFile(migrationUrl, "utf8");

  const reset = async () => {
    await pool.query(`TRUNCATE TABLE
      public.shopify_subscription_payment_trees,
      public.shopify_subscription_payments,
      public.shopify_tree_subscriptions,
      public.trees1,
      public.users1 RESTART IDENTITY CASCADE`);
  };
  const seedTrees = async (count, prefix = "TEST-TREE") => {
    const rows = [];
    for (let index = 1; index <= count; index += 1) {
      const result = await pool.query(`INSERT INTO public.trees1
        (tree_code, tree_type, lat, "long", planted_date, is_claimed)
        VALUES ($1, 'Cashew', 8.96356199, -12.52373404, DATE '2025-01-02', false)
        RETURNING id, tree_code`, [`${prefix}-${String(index).padStart(4, "0")}`]);
      rows.push(result.rows[0]);
    }
    return rows;
  };
  const payment = async (queryable, {
    order, contract, variant = "53296965386570", email = "subscription@example.test",
    paidAt = "2026-08-20T10:07:34+02:00", amount = "5.00"
  }) => (await queryable.query(`SELECT * FROM public.process_shopify_subscription_payment(
      $1, $2, $3, $4, $5::timestamptz, $6::numeric, NULL, NULL, 'EUR', 'ptb_subscription'
    )`, [order, contract, variant, email, paidAt, amount])).rows[0];

  try {
    await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public");
    await pool.query(`CREATE TABLE public.users1 (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name varchar, last_name varchar, email varchar NOT NULL UNIQUE,
      created_at timestamp without time zone NOT NULL DEFAULT now(),
      updated_at timestamp without time zone NOT NULL DEFAULT now()
    )`);
    await pool.query(`CREATE TABLE public.trees1 (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id integer REFERENCES public.users1(id), area varchar, lat numeric, "long" numeric,
      planted_date date, purchase_date timestamp without time zone, tree_code varchar,
      tree_id integer, tree_name varchar, tree_type varchar, unclaimed_user_id integer,
      created_at timestamp without time zone NOT NULL DEFAULT now(),
      updated_at timestamp without time zone NOT NULL DEFAULT now(),
      order_id varchar(50), reserved_token text, claimed_at timestamptz,
      is_claimed boolean DEFAULT false
    )`);
    await pool.query(migration);

    await t.test("1 migration creates tables, indexes, constraints and functions", async () => {
      const objects = await pool.query(`SELECT
        to_regclass('public.shopify_tree_subscriptions') IS NOT NULL AS subscriptions,
        to_regclass('public.shopify_subscription_payments') IS NOT NULL AS payments,
        to_regprocedure('public.process_shopify_subscription_payment(text,text,text,text,timestamp with time zone,numeric,text,text,text,text)') IS NOT NULL AS processor`);
      assert.deepEqual(objects.rows[0], { subscriptions: true, payments: true, processor: true });
    });

    await t.test("2 variant registry contains the three policies", async () => {
      const result = await pool.query("SELECT shopify_variant_id, amount::text, allocation_mode, trees_per_allocation FROM shopify_tree_subscription_variants ORDER BY amount");
      assert.equal(result.rowCount, 3);
      assert.deepEqual(result.rows.map(row => row.trees_per_allocation), [1, 1, 2]);
    });

    await t.test("3 €5 payments 1, 2 and 3 allocate 1, 0 and 1", async () => {
      await reset(); await seedTrees(3);
      const results = [];
      for (let n = 1; n <= 3; n += 1) results.push(await payment(pool, { order: `9100000000${n}`, contract: "90000000001" }));
      assert.deepEqual(results.map(row => [row.payment_number, row.trees_due, row.trees_allocated]), [[1,1,1],[2,0,0],[3,1,1]]);
      assert.deepEqual(results.map(row => row.welcome_required), [true, false, false]);
    });

    await t.test("4 €10 allocates one tree on two payments", async () => {
      await reset(); await seedTrees(3);
      const a = await payment(pool, { order: "92000000001", contract: "90000000002", variant: "53296965419338", amount: "10" });
      const b = await payment(pool, { order: "92000000002", contract: "90000000002", variant: "53296965419338", amount: "10" });
      assert.deepEqual([a.trees_due, b.trees_due, a.certificate_required, b.certificate_required], [1,1,true,false]);
    });

    await t.test("5 €20 allocates two distinct trees in one payment", async () => {
      await reset(); await seedTrees(3);
      const result = await payment(pool, { order: "93000000001", contract: "90000000003", variant: "53296965452106", amount: "20" });
      assert.equal(result.trees_allocated, 2);
      assert.equal(result.assigned_trees.length, 2);
      assert.equal(new Set(result.assigned_trees.map(tree => tree.tree_id)).size, 2);
    });

    await t.test("6 duplicate replay returns identical allocation", async () => {
      await reset(); await seedTrees(2);
      const input = { order: "94000000001", contract: "90000000004" };
      const first = await payment(pool, input); const retry = await payment(pool, input);
      assert.equal(retry.duplicate, true);
      assert.deepEqual(retry.assigned_trees, first.assigned_trees);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM shopify_subscription_payments")).rows[0].count, 1);
    });

    await t.test("7 duplicate with another contract is rejected without mutation", async () => {
      await reset(); await seedTrees(2);
      await payment(pool, { order: "95000000001", contract: "90000000005" });
      await assert.rejects(payment(pool, { order: "95000000001", contract: "90000000006" }), /different contract or variant/);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM shopify_subscription_payments")).rows[0].count, 1);
    });

    await t.test("8 unknown variant makes no mutation", async () => {
      await reset(); await seedTrees(1);
      await assert.rejects(payment(pool, { order: "96000000001", contract: "90000000007", variant: "99999999999" }), /Unknown or inactive/);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM users1")).rows[0].count, 0);
    });

    await t.test("9 insufficient €20 stock rolls back everything", async () => {
      await reset(); await seedTrees(1);
      await assert.rejects(payment(pool, { order: "97000000001", contract: "90000000008", variant: "53296965452106", amount: "20" }), /Insufficient free trees/);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM shopify_subscription_payments")).rows[0].count, 0);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM trees1 WHERE user_id IS NOT NULL")).rows[0].count, 0);
    });

    await t.test("10 every free-tree exclusion is respected", async () => {
      await reset();
      const user = (await pool.query("INSERT INTO users1(email) VALUES ('occupied@example.test') RETURNING id")).rows[0].id;
      await pool.query(`INSERT INTO trees1(tree_code,tree_type,lat,"long",is_claimed,user_id,purchase_date,order_id,reserved_token,claimed_at,unclaimed_user_id) VALUES
        ('EX-A','Cashew',1,1,false,$1,NULL,NULL,NULL,NULL,NULL),
        ('EX-B','Cashew',1,1,true,NULL,NULL,NULL,NULL,NULL,NULL),
        ('EX-C','Cashew',1,1,false,NULL,now(),NULL,NULL,NULL,NULL),
        ('EX-D','Cashew',1,1,false,NULL,NULL,'old',NULL,NULL,NULL),
        ('EX-E','Cashew',1,1,false,NULL,NULL,NULL,'token',NULL,NULL),
        ('EX-F','Cashew',1,1,false,NULL,NULL,NULL,NULL,now(),NULL),
        ('EX-G','Cashew',1,1,false,NULL,NULL,NULL,NULL,NULL,5),
        (NULL,'Cashew',1,1,false,NULL,NULL,NULL,NULL,NULL,NULL),
        ('EX-I','Cashew',NULL,1,false,NULL,NULL,NULL,NULL,NULL,NULL),
        ('EX-J','Cashew',1,NULL,false,NULL,NULL,NULL,NULL,NULL,NULL),
        ('ONLY-FREE','Cashew',1,1,false,NULL,NULL,NULL,NULL,NULL,NULL)`, [user]);
      const result = await payment(pool, { order: "98000000001", contract: "90000000009" });
      assert.equal(result.assigned_trees[0].tree_code, "ONLY-FREE");
    });

    await t.test("11 tree code is immutable", async () => {
      await reset(); await seedTrees(1, "TEST-IMMUTABLE-CODE");
      const result = await payment(pool, { order: "98100000001", contract: "90000000010" });
      assert.equal(result.assigned_trees[0].tree_code, "TEST-IMMUTABLE-CODE-0001");
      assert.equal((await pool.query("SELECT tree_code FROM trees1")).rows[0].tree_code, "TEST-IMMUTABLE-CODE-0001");
    });

    await t.test("12 GPS and planted date are preserved", async () => {
      await reset(); await seedTrees(1);
      const result = await payment(pool, { order: "98200000001", contract: "90000000011" });
      const tree = (await pool.query("SELECT lat::text, \"long\"::text, planted_date::text FROM trees1")).rows[0];
      assert.deepEqual(tree, { lat: "8.96356199", long: "-12.52373404", planted_date: "2025-01-02" });
      assert.equal(String(result.assigned_trees[0].latitude), "8.96356199");
    });

    await t.test("13 purchase_date is UTC regardless of session timezone", async () => {
      await reset(); await seedTrees(1);
      const client = await pool.connect();
      try { await client.query("SET TIME ZONE 'Pacific/Auckland'"); await payment(client, { order: "98300000001", contract: "90000000012" }); }
      finally { client.release(); }
      assert.equal((await pool.query("SELECT to_char(purchase_date,'YYYY-MM-DD HH24:MI:SS') AS value FROM trees1")).rows[0].value, "2026-08-20 08:07:34");
    });

    await t.test("14 updated_at changes on allocation", async () => {
      await reset(); await seedTrees(1);
      const before = (await pool.query("SELECT updated_at FROM trees1")).rows[0].updated_at;
      await new Promise(resolve => setTimeout(resolve, 10));
      await payment(pool, { order: "98400000001", contract: "90000000013" });
      const after = (await pool.query("SELECT updated_at FROM trees1")).rows[0].updated_at;
      assert.ok(after > before);
    });

    await t.test("15 two contracts sharing email keep independent counters", async () => {
      await reset(); await seedTrees(2);
      await payment(pool, { order: "98500000001", contract: "90000000014", email: "shared@example.test" });
      await payment(pool, { order: "98500000002", contract: "90000000015", email: "shared@example.test" });
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM users1")).rows[0].count, 1);
      assert.deepEqual((await pool.query("SELECT successful_payment_count FROM shopify_tree_subscriptions ORDER BY id")).rows.map(r => r.successful_payment_count), [1,1]);
    });

    await t.test("16 changed email keeps contract but links a new normalized user", async () => {
      await reset(); await seedTrees(2);
      await payment(pool, { order: "98600000001", contract: "90000000016", email: "person-old@example.test" });
      await payment(pool, { order: "98600000002", contract: "90000000016", email: "person-new@example.test" });
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM shopify_tree_subscriptions")).rows[0].count, 1);
      assert.equal((await pool.query("SELECT customer_email FROM shopify_tree_subscriptions")).rows[0].customer_email, "person-new@example.test");
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM users1")).rows[0].count, 2);
    });

    await t.test("17 side-effect update never reallocates", async () => {
      await reset(); await seedTrees(2);
      const input = { order: "98700000001", contract: "90000000017" };
      const first = await payment(pool, input);
      await pool.query("SELECT mark_shopify_subscription_payment_side_effect($1,'certificate','completed','test-id','https://example.invalid/test.pdf',NULL)", [input.order]);
      const retry = await payment(pool, input);
      assert.deepEqual(retry.assigned_trees, first.assigned_trees);
      assert.equal(retry.certificate_status, "completed");
    });

    await t.test("18 concurrent duplicate order creates one payment/allocation", async () => {
      await reset(); await seedTrees(3);
      const input = { order: "98800000001", contract: "90000000018" };
      const results = await Promise.all([payment(pool, input), payment(pool, input)]);
      assert.equal(results.filter(result => result.duplicate).length, 1);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM shopify_subscription_payments")).rows[0].count, 1);
      assert.equal((await pool.query("SELECT count(*)::int AS count FROM shopify_subscription_payment_trees")).rows[0].count, 1);
    });

    await t.test("19 concurrent distinct orders on one contract get 1 and 2", async () => {
      await reset(); await seedTrees(3);
      const [a,b] = await Promise.all([
        payment(pool, { order: "98900000001", contract: "90000000019", variant: "53296965419338", amount: "10" }),
        payment(pool, { order: "98900000002", contract: "90000000019", variant: "53296965419338", amount: "10" })
      ]);
      assert.deepEqual([a.payment_number,b.payment_number].sort(), [1,2]);
    });

    await t.test("20 SKIP LOCKED allocates another free tree", async () => {
      await reset(); const trees = await seedTrees(2);
      const locker = await pool.connect();
      try {
        await locker.query("BEGIN");
        await locker.query("SELECT id FROM trees1 WHERE id=$1 FOR UPDATE", [trees[0].id]);
        const result = await payment(pool, { order: "99000000001", contract: "90000000020" });
        assert.equal(result.assigned_trees[0].tree_id, trees[1].id);
      } finally { await locker.query("ROLLBACK"); locker.release(); }
    });
  } finally {
    await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public").catch(() => {});
    await pool.end();
  }
});

export { validatedLocalTestUrl };
