import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Tree allocated-tegel en directe route bestaan binnen beveiligde dashboardstructuur", async () => {
  const sales = await readFile(new URL("../frontend/automation-dashboard/tree-sales/index.html", import.meta.url), "utf8");
  const page = await readFile(new URL("../frontend/automation-dashboard/tree-sales/tree-allocated/index.html", import.meta.url), "utf8");
  const script = await readFile(new URL("../frontend/automation-dashboard/tree-sales/tree-allocated/tree-allocated.js", import.meta.url), "utf8");
  const netlify = await readFile(new URL("../netlify.toml", import.meta.url), "utf8");
  assert.match(sales, /href="\/automation-dashboard\/tree-sales\/tree-allocated\/"/);
  assert.match(page, /<h1>Tree allocated<\/h1>/);
  assert.match(page, /tree-allocated\.js/);
  assert.match(page, /Niet volledig controleerbaar/);
  assert.match(page, />Periode</);
  assert.match(page, /<option value="all">Alle perioden<\/option>/);
  assert.match(page, /name="language" disabled/);
  assert.match(page, /name="sku"[^>]*disabled/);
  assert.match(page, /<option value="completed">Volledig<\/option>/);
  assert.match(page, /Gift-claim e-mail/);
  assert.match(page, /certificaatmail worden nog niet gemonitord/);
  assert.match(script, /Shopify orderdatum<\/dt><dd>\$\{formatDate\(order\.order_date\)\}/);
  assert.match(script, /Toewijzing waargenomen op/);
  assert.match(script, /Bron niet gekoppeld/);
  assert.match(script, /Gift-claim e-mail aangeboden/);
  assert.match(script, /Aangeboden voor verzending/);
  assert.match(script, /function renderOperationalChecks/);
  assert.match(script, /shopify_source_available \? badge\("green", "✓", "Gelukt"\)/);
  assert.match(script, /Certificaat gegenereerd", "Niet gemonitord", "Niet gemonitord"/);
  assert.match(script, /Certificaatmail aangeboden", "Niet gemonitord", "Niet gemonitord"/);
  assert.doesNotMatch(script, /Volledig afgehandeld|E-mail aangeboden voor verzending/);
  assert.doesNotMatch(page, /certificaatmail aantoonbaar compleet|>Volledig afgehandeld<|>Afgerond</);
  assert.doesNotMatch(script, /<dt>Orderdatum<\/dt><dd>\$\{formatDate\(order\.allocation_observed_at\)\}/);
  assert.match(netlify, /path = "\/automation-dashboard\/\*"/);
});
