import { read, readTrees } from "./db.js";
import { buildTreeSales, detailForSale, troubleshootingPrompt, saleTypeForSku } from "./tree-sales-model.js";
import { OWN_TREE_WORKFLOW } from "./tree-sales-workflows.js";
import { getSaleDiagnostics } from "./tree-sales-diagnostics.js";
const ORDERS=`select distinct on (entity_id) entity_id::text as order_id,customer_email as email,changed_fields->>'created_at' as purchased_at,changed_fields->>'sku' as sku,(changed_fields->>'ordered_quantity')::int as tree_count from monitoring.automation_events where entity_type='shopify_order' and category='shopify_order_received' order by entity_id,event_time desc,id desc`;
const FAILURES=`select entity_id::text as order_id,true as workflow_failed,max(event_time) as workflow_event_at,max(error_message) filter(where nullif(error_message,'') is not null) as workflow_error from monitoring.automation_events where entity_type='shopify_order' and (lower(status) in('failed','error','blocked','halted') or lower(severity)='red') group by entity_id`;
const TREES=`select order_id::text as order_id,count(*)::int as allocated_count,max(coalesce(claimed_at,updated_at,created_at)) as processed_at from public.trees1 where order_id::text=any($1::text[]) group by order_id`;
const attempt=async(fn)=>{try{return{available:true,result:await fn()};}catch{return{available:false,result:{rows:[]}};}};
export async function listTreeSales(deps={}){const monitoring=deps.read||read,trees=deps.readTrees||readTrees,orders=await monitoring(ORDERS);if(!orders.rows.length)return{sales:[],optimisation:[]};const rows=orders.rows.filter(x=>saleTypeForSku(x.sku)),groups={gift:rows.filter(x=>saleTypeForSku(x.sku)==='gift'),own:rows.filter(x=>saleTypeForSku(x.sku)==='own')},failures=await attempt(()=>monitoring(FAILURES)),evidence=Object.fromEntries(await Promise.all(Object.entries(groups).map(async([type,list])=>[type,list.length?await attempt(()=>trees(TREES,[list.map(x=>x.order_id)])):{available:true,result:{rows:[]}}]))),index=x=>new Map(x.map(y=>[y.order_id,y])),failed=index(failures.result.rows);return{sales:buildTreeSales(rows.map(order=>{const type=saleTypeForSku(order.sku),tree=index(evidence[type].result.rows).get(order.order_id),failure=failed.get(order.order_id);return{...order,allocated_count:tree?.allocated_count,processed_at:tree?.processed_at||null,tree_evidence_available:evidence[type].available,workflow_evidence_available:failures.available,workflow_failed:Boolean(failure),workflow_event_at:failure?.workflow_event_at||null,workflow_error:failure?.workflow_error||null,workflow_id:type==='gift'?'zap_47':OWN_TREE_WORKFLOW.key,workflow_maintenance:type==='own'?OWN_TREE_WORKFLOW:null};})),optimisation:[]};}
export async function getTreeSale(orderId,deps={}){const response=await listTreeSales(deps),sale=response.sales.find(x=>x.order_id===String(orderId));if(!sale)return null;const diagnostics=sale.status==='GREEN'?null:await getSaleDiagnostics(sale,deps);return{sale,detail:detailForSale(sale),prompt:troubleshootingPrompt(sale),diagnostics,optimisation:response.optimisation};}
