import { element as el, clear, formatTime } from './view.js';
import { GROUPS, LINKS, buildTasks, groupTasks } from './workspace-model.js';
const main = document.querySelector('#main');
let data = null, tasks = [], loading = false, requestId = 0;
const text = (tag, value, className='') => el(tag,{text:value,className});
const box = (...children) => el('section',{className:'card'},children);
const link = (label, href, danger=false) => el('a',{text:label,className:'button '+(danger?'danger':'secondary'),attributes:{href,...(href.startsWith('https:')?{target:'_blank',rel:'noopener noreferrer'}:{})}});
const actionLink = t => link(t.title+' →','#task/'+encodeURIComponent(t.id),true);
const badge = (red,label) => text('span',(red?'! ':'✓ ')+label,'pill'+(red?' red':''));
function heading(title, subtitle, pnb=false) {
  return el('div',{className:'heading'},[el('div',{},[text('h1',title),text('p',subtitle,'sub')]),pnb?el('img',{className:'brand-pnb',attributes:{src:'assets/pnb.png',alt:'Plant N Boom'}}):null]);
}
function notice(message){return text('p',message,'note');}
function taskList(list){return el('div',{className:'stack'},list.map(t=>box(actionLink(t),notice('Owner: '+t.owner+(t.date?' · Recorded: '+formatTime(t.date):'')))));}
function statusCard(title,id,subtitle){const list=groupTasks(tasks,id);return el('a',{className:'card card-link'+(list.length?' red-card':''),attributes:{href:'#'+id}},[text('h2',title),badge(list.length>0,list.length?'Action needed':'No action needed'),notice(subtitle),notice(list.length?list.length+' follow-up item(s) →':'No open actions in the connected checks.')]);}
async function request(url){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});const body=await r.json().catch(()=>null);if(!r.ok||!body?.ok)throw new Error(r.status===401?'Sign in again to load the console.':'The console could not load this information.');return body;}
export async function refresh(){if(loading)return;loading=true;document.querySelector('#refresh').disabled=true;data=null;tasks=[];render();try{const body=await request('/.netlify/functions/workspace');data=body.workspace;tasks=buildTasks(data);document.querySelector('#updated').textContent='Last checked: '+formatTime(body.generated_at)+' · Amsterdam time';}catch{document.querySelector('#updated').textContent='Checks could not be refreshed';data={sources:{},partners:{configured:false,records:[]},minimum_free_trees:0};tasks=buildTasks(data);}finally{loading=false;document.querySelector('#refresh').disabled=false;render();}}
function overview(){main.append(heading('What needs my attention?','Open a red signal to see what you need to do.'));const summary=el('section',{className:'banner'+(tasks.length?'':' good')},[text('h2',tasks.length?tasks.length+' follow-up items':'No action needed'),link('Open action list','#actions',!!tasks.length)]);main.append(summary,el('div',{className:'heading'},[text('h2','Plant N Boom'),el('img',{className:'brand-pnb',attributes:{src:'assets/pnb.png',alt:'Plant N Boom'}})]),el('div',{className:'grid'},GROUPS.map(g=>statusCard(g.title,g.id,g.title==='Tree sales'?'Orders and tree allocation':g.title==='Subscriptions'?'Recurring payments and tree assignments':g.title==='Certificates'?'Certificates and delivery':'Customer details and CRM updates'))),el('div',{className:'module-section'},[statusCard('Academy & uploads','academy','Upload approvals and student questions')]));}
function processPage(id){const group=GROUPS.find(g=>g.id===id),list=groupTasks(tasks,id);main.append(heading(group.title,'Tasks from the connected monitoring records.',true),list.length?taskList(list):box(badge(false,'No action needed'),notice('No open action was found in these checks.')),link('Back to overview','#overview'));}
function academy(){main.append(heading('Academy & uploads','Review submissions, help students and open your galleries.'));const s=data.sources;const count=k=>s[k]?.available?s[k].data.count:null;const review=count('uploads'),questions=count('questions');main.append(el('div',{className:'grid'},[
  box(text('h2','Review uploads'),badge(review!==0,review===null?'Restore review count':review?review+' awaiting review':'No action needed'),notice('Admin Gallery: review submissions before publication.'),link('Open review queue ↗',LINKS.reviews,review!==0),link('Open Admin Gallery ↗',LINKS.admin)),
  box(text('h2','Student questions'),badge(questions!==0,questions===null?'Restore question count':questions?questions+' awaiting a reply':'No action needed'),notice('Read each question and send a checked answer.'),link('Open tutor queue ↗',LINKS.questions,questions!==0)),
  box(text('h2','Student Gallery'),notice('Approved student assignments and progress.'),link('Open Student Gallery ↗',LINKS.student)),
  box(text('h2','KETSO Gallery'),notice('Published staff and project updates.'),link('Open KETSO Gallery ↗',LINKS.gallery)),
  box(text('h2','Upload photos or videos'),notice('Submit an assignment or share a field update.'),link('Open uploader ↗',LINKS.uploader),link('Staff uploads ↗',LINKS.staff)),
  box(text('h2','Your Academy actions'),taskList(groupTasks(tasks,'academy')))
]));}
function treeMap(){const s=data.sources.trees,count=s?.available?s.data.count:null,list=groupTasks(tasks,'tree-map');main.append(heading('Tree Map','Plant N Boom',true),box(text('h2','Free trees available to assign'),text('p',count===null?'Count unavailable':new Intl.NumberFormat('en-GB').format(count),'stock-number'),notice('Located trees without an owner and without a tree name. A tree code is an inventory identifier and may be present.'),count!==null?badge(list.length>0,list.length?'Arrange more trees':'No action needed'):null,notice('Stock alert level: '+data.minimum_free_trees+' trees or fewer.'),link('Open live Tree Map ↗',LINKS.map)),taskList(list));}
const money=value=>Number.isFinite(Number(value))&&value!==null?new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(value)):'Not recorded';
function partnerTable(rows){const table=el('table',{},[el('thead',{},[el('tr',{},['Organisation','Funding target','Received','Next action','Owner / deadline'].map(v=>el('th',{text:v,attributes:{scope:'col'}})))])]);table.append(el('tbody',{},rows.map(p=>el('tr',{},[el('th',{text:p.name,attributes:{scope:'row'}}),text('td',money(p.target_eur)),text('td',money(p.received_eur)),el('td',{},[p.next_action?link(p.next_action,'#task/'+encodeURIComponent('partner-'+p.id),true):badge(false,'No action needed')]),text('td',(p.owner||'Not assigned')+' · '+(p.due_date||'No deadline recorded'))]))));return el('div',{className:'table-scroll'},[table]);}
function csr(){const p=data.partners;main.append(heading('Businesses & foundations','Current supporters, prospective supporters and funding targets.'));main.append(taskList(groupTasks(tasks,'csr')));for(const [value,title] of [['supporter','Current supporters'],['prospect','Target list: prospective supporters']]){const rows=(p.records||[]).filter(r=>r.relationship===value);main.append(box(text('h2',title),rows.length?partnerTable(rows):notice(p.configured?'No organisations recorded in this list.':'The approved list has not been connected yet.')));}main.append(notice('Prospective funding is not confirmed income. Last list review: '+formatTime(p.reviewed_at)));}
function promptFor(t){return ['Start with Workflow Maintenance for netlify_ops_console and the affected process.','Investigate this Ops Console action: '+t.title,'Observed: '+t.observed,'Workflow ID: '+(t.workflow_id||'Identify from the registry'),'Owner: '+t.owner,'Site: ketso-ops-console.netlify.app. App: apps/ops-console in eamonnhanson/ptb-tree-map.','Read the connection inventory and runbook. Confirm the database and read-only role. Do not paste credentials or personal customer data.','Inspect the evidence, explain the cause in plain English, then prepare the smallest fix on a dedicated branch. Run only the relevant check and build.','Do not replay payments, allocate trees, send emails, change database permissions, merge or deploy without explicit approval.','Provide exact manual steps and record the outcome in Workflow Maintenance.'].join('\n');}
function taskPage(id,technical=false){const t=tasks.find(t=>t.id===id);if(!t){main.append(heading('This action is no longer in the current list','Refresh the overview to see the latest tasks.'),link('Back to overview','#overview'));return;}main.append(heading(t.title,technical?'Instructions for the maintainer':'Owner: '+t.owner));if(!technical){main.append(box(text('h2','What was expected?'),text('p',t.url?'The queue is handled and no item needs your response.':'The process can be checked and any recorded follow-up has been handled.'),text('h2','What is recorded?'),text('p',t.observed),t.date?notice('Record date: '+formatTime(t.date)):null,text('h2','What should I do?'),text('p',t.action),t.url?link('Open the working screen ↗',t.url,true):null,link('Open instructions','#technical/'+encodeURIComponent(t.id),true)));}else{const prompt=el('textarea',{className:'prompt',attributes:{readonly:'',rows:'12','aria-label':'Prompt for ChatGPT or Codex'}});prompt.value=promptFor(t);const copy=el('button',{text:'Copy prompt',className:'button',attributes:{type:'button'}});copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(prompt.value);copy.textContent='Copied';}catch{prompt.focus();prompt.select();copy.textContent='Select the text and copy';}});main.append(box(text('h2','Manual instructions'),el('ol',{className:'steps'},[text('li','Open Workflow Maintenance and find the relevant process.'),text('li',t.action),text('li','Check the actual result before retrying anything. Record who checked it and when.'),text('li','Refresh this console. If a historical action still appears, reconcile its source record through the approved maintenance procedure.')]),link('Open Workflow Maintenance ↗',LINKS.maintenance)),box(text('h2','Ask ChatGPT or Codex'),prompt,copy));if(t.workflow_id)loadEvidence(t.workflow_id,requestId);if(t.record)main.append(box(text('h2','Source record'),text('pre',JSON.stringify({source:t.record.source,id:t.record.source_id,status:t.record.status,date:t.record.occurred_at,workflow:t.record.workflow},null,2))));}main.append(link('Back to actions','#actions'));}
async function loadEvidence(id,renderId){const holder=box(text('h2','Technical records'),notice('Loading records…'));main.append(holder);try{const r=await request('/.netlify/functions/workflow-detail?id='+encodeURIComponent(id));if(renderId!==requestId)return;clear(holder);holder.append(text('h2','Technical records'));for(const [title,c] of [['Dependencies',r.detail.dependencies],['Code references',r.detail.implementation?.code_assets],['Runbooks',r.detail.implementation?.runbooks],['Reviews',r.detail.verification],['Recent events',r.detail.runtime]]){const section=el('details',{},[el('summary',{text:title})]);section.append(c?.rows?.length?text('pre',JSON.stringify(c.rows,null,2)):notice('No records returned.'));if(c?.truncated)section.append(notice('Results truncated at '+c.limit+'.'));holder.append(section);}}catch{if(renderId===requestId){clear(holder);holder.append(text('h2','Technical records could not be loaded'),notice('Ask the maintainer to check the workflow-detail function log.'));}}}
function render(){requestId++;clear(main);let [route='overview',raw='']=location.hash.slice(1).split('/');route=route||'overview';let id;try{id=decodeURIComponent(raw);}catch{id='';}document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+route;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(loading||!data){main.append(heading('Checking your action lists…',''));return;}if(route==='overview')overview();else if(GROUPS.some(g=>g.id===route))processPage(route);else if(route==='academy')academy();else if(route==='tree-map')treeMap();else if(route==='csr')csr();else if(route==='task'||route==='technical')taskPage(id,route==='technical');else if(route==='actions')main.append(heading('Your action list','Operational work and monitoring follow-up. Records retain their original dates.'),tasks.length?taskList(tasks):box(badge(false,'No action needed')));else if(route==='upload')main.append(heading('Upload photos or videos','Choose your existing upload screen.'),box(link('Open content uploader ↗',LINKS.uploader),link('Open staff uploads ↗',LINKS.staff)));else main.append(heading('Page not found',''),link('Back to overview','#overview'));}
window.addEventListener('hashchange',()=>{render();main.focus();window.scrollTo(0,0);});
document.querySelector('#refresh').addEventListener('click',refresh);
refresh();
