import test from "node:test";
import assert from "node:assert/strict";
import { createHandler } from "../functions/gift-claims-schema-diagnostics.js";
const original={user:process.env.OPS_CONSOLE_USER,password:process.env.OPS_CONSOLE_PASSWORD};
const event={httpMethod:"GET",headers:{authorization:`Basic ${Buffer.from("operator:secret").toString("base64")}`}};
test.beforeEach(()=>{process.env.OPS_CONSOLE_USER="operator";process.env.OPS_CONSOLE_PASSWORD="secret";});
test.after(()=>{process.env.OPS_CONSOLE_USER=original.user;process.env.OPS_CONSOLE_PASSWORD=original.password;});
test("schema diagnostics requires authenticated GET",async()=>{assert.equal((await createHandler()({httpMethod:"GET",headers:{}})).statusCode,401);assert.equal((await createHandler()({...event,httpMethod:"POST"})).statusCode,405);});
test("schema diagnostics returns safe metadata without credentials",async()=>{const handler=createHandler({query:async sql=>sql.includes("current_database")?{rows:[{database:"defaultdb",current_user:"reader"}]}:sql.includes("to_regclass")?{rows:[{relation:"gift_claims"}]}:{rows:[{column_name:"order_id",data_type:"text",is_nullable:"NO"}]}});const body=JSON.parse((await handler(event)).body),output=JSON.stringify(body);assert.deepEqual(body.columns,[{column_name:"order_id",data_type:"text",is_nullable:"NO"}]);assert.doesNotMatch(output,/password|postgres:|sslmode|BEGIN CERTIFICATE/i);});
test("missing relation remains safe metadata",async()=>{const handler=createHandler({query:async sql=>sql.includes("current_database")?{rows:[{database:"defaultdb",current_user:"reader"}]}:sql.includes("to_regclass")?{rows:[{relation:null}]}:{rows:[]}});const body=JSON.parse((await handler(event)).body);assert.equal(body.relation,null);assert.deepEqual(body.columns,[]);});
