import test from "node:test";
import assert from "node:assert/strict";
import { diagnosticSql, getSaleDiagnostics } from "../functions/_shared/tree-sales-diagnostics.js";

const sale = { order_id: "18105221349706", email: "buyer@example.test", tree_count: 10, purchased_at: "2026-09-13T10:00:00Z" };
const trees = [{ id: 1, tree_code: "A", order_id: sale.order_id, user_id: 9, recipient_email: "recipient-a@example.test", is_claimed: true, claimed_at: "2026-09-13T11:00:00Z", created_at: "2026-09-13T10:05:00Z", updated_at: "2026-09-13T11:00:00Z" }, { id: 2, tree_code: "B", order_id: sale.order_id, user_id: null, recipient_email: null, is_claimed: false, claimed_at: null, created_at: "2026-09-13T10:06:00Z", updated_at: "2026-09-13T10:06:00Z" }];
function dependencies({ failAssignments = false, linked = trees, onTreeQuery } = {}) { return { readTrees: async (sql) => { onTreeQuery?.(sql); if (sql.includes("with buyer")) { if (failAssignments) throw new Error("database unavailable"); return { rows: [{ buyers: [{ id: 1, email: sale.email }], buyer_trees: [], recipient_emails: ["recipient-a@example.test", "recipient-b@example.test"] }] }; } return { rows: linked }; }, read: async () => ({ rows: [{ category: "shopify_order_received", status: "confirmed", event_time: "2026-09-13T10:00:01Z", error_message: null }] }) }; }

test("allocation reports a 10 purchased, 7 linked discrepancy", async () => { const linked = Array.from({ length: 7 }, (_, id) => ({ ...trees[id % 2], id })); const result = await getSaleDiagnostics(sale, dependencies({ linked })); assert.equal(result.allocation.status, "ISSUE FOUND"); assert.equal(result.allocation.difference, 3); });
test("allocation passes when linked quantity matches purchase", async () => { const matching = Array.from({ length: 10 }, (_, id) => ({ ...trees[id % 2], id })); const result = await getSaleDiagnostics(sale, dependencies({ linked: matching })); assert.equal(result.allocation.status, "PASS"); assert.equal(result.allocation.difference, 0); });
test("gift buyer without directly assigned trees is information, not an error", async () => { const result = await getSaleDiagnostics(sale, dependencies()); assert.equal(result.assignments.status, "INFORMATION"); assert.match(result.assignments.conclusion, /can be normal for a gift-tree purchase/i); });
test("assignment evidence preserves multiple recipients", async () => { const result = await getSaleDiagnostics(sale, dependencies()); assert.deepEqual(result.assignments.recipient_emails, ["recipient-a@example.test", "recipient-b@example.test"]); });
test("allocation counts claimed and unclaimed trees", async () => { const result = await getSaleDiagnostics({ ...sale, tree_count: 2 }, dependencies()); assert.equal(result.allocation.claimed_count, 1); assert.equal(result.allocation.unclaimed_count, 1); });
test("claimed count follows the source is_claimed column", async () => { const queries = [], linked = [{ ...trees[0], is_claimed: true, claimed_at: null }, { ...trees[1], is_claimed: false, claimed_at: "2026-09-13T11:00:00Z" }], result = await getSaleDiagnostics({ ...sale, tree_count: 2 }, dependencies({ linked, onTreeQuery: (query) => queries.push(query) })); assert.equal(result.allocation.claimed_count, 1); assert.equal(result.allocation.unclaimed_count, 1); assert.equal(result.allocation.claim_state_inconsistency_count, 2); const orderQuery = queries.find((query) => query.includes("left join public.users1")); assert.match(orderQuery, /t\.is_claimed as is_claimed/); assert.doesNotMatch(orderQuery, /claimed_at is not null\) as is_claimed/); });
test("is_claimed true with no timestamp remains claimed", async () => { const result = await getSaleDiagnostics({ ...sale, tree_count: 1 }, dependencies({ linked: [{ ...trees[0], is_claimed: true, claimed_at: null }] })); assert.equal(result.allocation.claimed_count, 1); });
test("is_claimed false with a timestamp remains unclaimed", async () => { const result = await getSaleDiagnostics({ ...sale, tree_count: 1 }, dependencies({ linked: [{ ...trees[1], is_claimed: false, claimed_at: "2026-09-13T11:00:00Z" }] })); assert.equal(result.allocation.claimed_count, 0); assert.equal(result.allocation.unclaimed_count, 1); });
test("diagnostics expose claim state but never access tokens", async () => { const result = await getSaleDiagnostics(sale, dependencies()); assert.match(JSON.stringify(result.allocation.trees), /is_claimed/); assert.doesNotMatch(JSON.stringify(result), /claimed_token|reserved_token/i); });
test("timeline is chronological and does not invent a batch", async () => { const result = await getSaleDiagnostics(sale, dependencies()); assert.equal(result.timeline.status, "INFORMATION"); assert.match(result.timeline.conclusion, /do not prove a separate reservation batch/i); assert.deepEqual(result.timeline.entries.map((entry) => entry.at), [...result.timeline.entries.map((entry) => entry.at)].sort()); });
test("a failed assignment diagnostic does not hide allocation or timeline", async () => { const result = await getSaleDiagnostics(sale, dependencies({ failAssignments: true })); assert.equal(result.assignments.status, "UNAVAILABLE"); assert.equal(result.allocation.status, "ISSUE FOUND"); assert.equal(result.timeline.status, "INFORMATION"); });
test("copyable diagnostic SQL is select-only and uses the known order and email", () => { const sql = diagnosticSql(sale); assert.match(sql, /18105221349706/); assert.match(sql, /buyer@example\.test/); assert.match(sql, /^-- Order allocation\nselect/im); assert.doesNotMatch(sql, /\b(update|insert|delete|drop|alter)\b/i); });
